# Generated by Django 3.0.11 on 2020-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(related_name='recipes', through='receipe.IngredientsRecipe', to='receipe.Ingredients'),
        ),
    ]
