# Generated by Django 3.0.11 on 2020-11-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients_receipe',
            new_name='IngredientsReceipe',
        ),
    ]
