# Generated by Django 3.0.11 on 2020-11-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_auto_20201106_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsreceipe',
            name='receipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipe', to='receipe.Receipe'),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient_list',
        ),
        migrations.AddField(
            model_name='receipe',
            name='ingredient_list',
            field=models.ManyToManyField(through='receipe.IngredientsReceipe', to='receipe.Ingredients'),
        ),
    ]
