# Generated by Django 3.0.11 on 2020-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_auto_20201106_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True),
        ),
    ]
