# Generated by Django 3.0.11 on 2020-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0004_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='orange', max_length=20),
        ),
    ]
