# Generated by Django 3.0.11 on 2020-11-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0005_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default='breakfast', max_length=20),
        ),
    ]
