# Generated by Django 3.0.11 on 2020-11-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0006_tag_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='breakfast', max_length=10),
        ),
    ]
