# Generated by Django 3.0.11 on 2020-11-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0007_auto_20201108_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
    ]
