# Generated by Django 3.0.11 on 2020-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0009_auto_20201108_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='receipe',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
